apiVersion: apps/v1
kind: Deployment
metadata:
  name: javatest-deployment
  namespace: javatest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javatest
  template:
    metadata:
      labels:
        app: javatest
    spec:
      containers:
        - name: javatest
          image: java:11
          imagePullPolicy: Never
          ports:
            - containerPort: 9090