apiVersion: v1
kind: Service
metadata:
  name: javatest-service
  namespace: javatest
spec:
  type: NodePort
  selector:
    app: javatest
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30007