all:
  hosts:
    windows_vm:
      ansible_host: "{{ lookup('env','WIN_HOST') }}"
      ansible_user: "{{ lookup('env','WIN_USER') }}"
      ansible_port: 5986
      ansible_connection: winrm
      ansible_winrm_transport: certificate
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_cert_pem: "{{ lookup('env','WIN_CERT') }}"
      ansible_winrm_cert_key_pem: "{{ lookup('env','WIN_CERT') }}"
      ansible_winrm_cert_passphrase: "{{ lookup('env','WIN_CERT_PASS') }}"