name: CI-CD Ansible Deployment

on:
  push:
    branches:
      - feature/javawin

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: configure java and maven 
        run: | 
          sudo apt update
          sudo apt install -y openjdk-17-jdk -y
          sudo apt install -y maven  


      - name: Build with Maven
        run: mvn clean package

      - name: upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          pip install pywinrm requests-ntlm

      - name: Create certificate file from secret
        run: |
          echo "${{ secrets.WINRM_CERT }}"
          echo "${{ secrets.WINRM_CERT }}" | base64 -d > win11.crt

      - name: Run Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          WIN_PASSWORD: ${{ secrets.WIN_PASSWORD }}
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

          ansible-playbook  -i ansible/inventory.ini \
            ansible/deploy.yml