name: CI-CD Ansible Deployment

on:
  push:
    branches:
      - feature/javawin

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Install Ansible
      #   run: |
      #     sudo apt update
      #     sudo apt install -y ansible
      #     pip install pywinrm requests-ntlm

      - name: Create certificate file from secret
        run: |
          echo "${{ secrets.WINRM_CERT }}"
          echo "${{ secrets.WINRM_CERT }}" | base64 -d > win11.crt

      - name: Run Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

          ansible windows -i ansible/inventory.ini \
            -e ansible_password="${{ secrets.WIN_PASSWORD }}" \
            -m win_ping